apiVersion: v1
kind: ServiceAccount
metadata:
  name: rtsa-sa
  namespace: red-team-saas
  labels:
    app: red-team-saas
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rtsa-role
  namespace: red-team-saas
  labels:
    app: red-team-saas
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rtsa-rolebinding
  namespace: red-team-saas
  labels:
    app: red-team-saas
subjects:
  - kind: ServiceAccount
    name: rtsa-sa
    namespace: red-team-saas
roleRef:
  kind: Role
  name: rtsa-role
  apiGroup: rbac.authorization.k8s.io
