"""GitHub integration — Phase 16"""
from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Optional

import aiohttp

from app.services.integrations.base_integration import BaseIntegration

_GITHUB_API = "https://api.github.com"


class GitHubIntegration(BaseIntegration):
    """Create GitHub Issues and interact with repositories via the REST API."""

    async def test_connection(self) -> bool:
        try:
            async with aiohttp.ClientSession() as session:
                async with session.get(
                    f"{_GITHUB_API}/user",
                    headers=self._headers(),
                    timeout=aiohttp.ClientTimeout(total=10),
                ) as resp:
                    return resp.status == 200
        except Exception:
            return False

    async def send_message(self, message: str, **kwargs) -> Dict[str, Any]:
        """GitHub has no direct messaging; returns unsupported."""
        return self._failure("send_message not supported for GitHub; use create_issue", "NOT_SUPPORTED")

    async def create_issue(
        self,
        title: str,
        description: str,
        severity: Optional[str] = None,
        cve_id: Optional[str] = None,
        labels: Optional[List[str]] = None,
        assignee: Optional[str] = None,
        **kwargs,
    ) -> Dict[str, Any]:
        repo = self.config.get("repository", "")
        if not repo:
            return self._failure("repository not configured in integration config", "CONFIG_ERROR")

        # Build label list
        issue_labels: List[str] = ["security"]
        if severity:
            issue_labels.append(f"severity-{severity.lower()}")
        if cve_id:
            issue_labels.append("cve")
        if labels:
            issue_labels.extend(labels)

        body = (
            f"## {title}\n\n"
            f"### Description\n{description}\n\n"
            f"### Severity\n{severity or 'Unknown'}\n\n"
            f"### CVE\n{cve_id or 'N/A'}\n\n"
            f"### Metadata\n"
            f"- **Source**: Red Team SaaS\n"
            f"- **Generated**: {datetime.utcnow().isoformat()}\n\n"
            f"---\n*Auto-generated by Red Team SaaS*"
        )

        payload: Dict[str, Any] = {"title": title, "body": body, "labels": issue_labels}
        if assignee:
            payload["assignee"] = assignee

        try:
            async with aiohttp.ClientSession() as session:
                async with session.post(
                    f"{_GITHUB_API}/repos/{repo}/issues",
                    json=payload,
                    headers=self._headers(),
                    timeout=aiohttp.ClientTimeout(total=15),
                ) as resp:
                    data = await resp.json()
                    if resp.status == 201:
                        return self._success(
                            external_id=str(data.get("number")),
                            external_url=data.get("html_url"),
                        )
                    return self._failure(
                        data.get("message", f"HTTP {resp.status}"),
                        str(resp.status),
                    )
        except Exception as exc:
            return self._failure(str(exc))

    async def get_auth_url(self) -> str:
        client_id = self.config.get("client_id", "YOUR_CLIENT_ID")
        return (
            f"https://github.com/login/oauth/authorize"
            f"?client_id={client_id}&scope=repo"
        )

    # ── Helpers ───────────────────────────────────────────────────────────────

    def _headers(self) -> Dict[str, str]:
        return {
            "Authorization": f"token {self.auth_token}",
            "Accept": "application/vnd.github.v3+json",
        }
